name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
         xcodebuild -workspace RickAndMortyFinalApp.xcworkspace -scheme RickAndMortyFinalApp -configuration Debug build test \
  -destination 'platform=iOS Simulator,name=iPhone 8'
      - name: Test
        run: |
           xcodebuild -workspace RickAndMortyFinalApp.xcworkspace -scheme RickAndMortyFinalApp -configuration Debug build test \
  -destination 'platform=iOS Simulator,name=iPhone 8'
